### ISSUE TITLE
Changes required on Footer 

### ISSUE THREAD

**Issue by lovelymahor** [4darsh-Dev/CogniGaurd#53] opened 2024-06-06 06:32 UTC
The current color contrast of the footer text is inadequate, making the font color difficult to read. Please assign the task to adjust the color contrast to ensure the font is clearly visible against the background.
The overall format of the footer needs improvement for better aesthetics and functionality. Please update the layout to ensure it is well-organized and aligns with the website’s design standards.

![Screenshot_2024-06-06-12-00-18-55_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/4darsh-Dev/CogniGaurd/assets/141830010/d4abe26e-ca6d-47dd-8565-ffd3c286b675)

Also please add the labels gssoc and the level which you find appropriate for this issue. thank you!

**Comment by 4darsh-Dev** [comment] 2024-06-07 09:20
@lovelymahor  actually the issue is it is not responsive on mobile devices, yet, 
if you want to work on this, you can make the footer and navbar responsive using css media queries and js . 
for navbar you can create a hamburger menu button, 
for rest of the page you can adjust the size of the containers. 
-- have you worked on html, css and js earlier ?

**Comment by lovelymahor** [comment] 2024-06-07 09:46
yes, I want to work on this

**Comment by 4darsh-Dev** [comment] 2024-06-08 10:11
okay, assigned to you @lovelymahor

**Comment by lovelymahor** [comment] 2024-06-08 14:33
Okay thankyou

**Comment by 4darsh-Dev** [comment] 2024-06-13 18:12
@lovelymahor  any work update?

**Comment by TheNikhilRaj** [comment] 2024-06-21 12:29
I would like to work on this issue, please assign this to me.
@4darsh-Dev

**Comment by 4darsh-Dev** [comment] 2024-06-22 09:25
@TheNikhilRaj  already fixed, if found any additions explain them .

**Comment by 4darsh-Dev** [comment] 2024-06-26 06:21
⚠️[URGENT]⚠️ Reminder for GSSoC 24' Contributors Please join our CogniGuard Project #general GSSoC'24 Discord channel:
 Here you can discuss your queries and doubts with your mentors. 
 See #109 issues section.

**Comment by 4darsh-Dev** [comment] 2024-06-26 06:23
⚠️[URGENT]⚠️ Reminder for GSSoC 24' Contributors Please join our CogniGuard Project #general GSSoC'24 Discord channel:
 Here you can discuss your queries and doubts with your mentors. 
 See #109 issues section.

**Comment by 4darsh-Dev** [comment] 2024-07-27 04:38
Hey @lovelymahor ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Closed** 2024-07-27 04:37 UTC
Labels: enhancement, gssoc
